Gráficos básicos pt2


----
boxplot
 -> compreender como os dados estão distribuídos
```{r}
boxplot(trees$Volume, main = "Árvores", xlab = "Volume")
boxplot(trees$Volume, main = "Árvores", xlab = "Volume", col = "blue", horizontal = TRUE)
boxplot(trees$Volume, main = "Árvores", xlab = "Volume", col = "blue", outline = F)
```

```{r}
boxplot(trees$Height, main = "Árvores", xlab = "Altura", col = "blue", notch = TRUE) #o notch gera um talho no boxplot

boxplot.stats(trees$Height) #dados do gráfico

boxplot.stats(trees$Height)$stats #lê apenas uma das informações
```
Vários dados de uma vez
```{r}
boxplot(trees)
```
Agregação
 -> para agregagar dados bagunçados
```{r}
InsectSprays #vemos que os dados não estão somados, estão apenas fornecidos
spray = aggregate(. ~ spray, data=InsectSprays, sum) #". ~ spray" vai considerar a variável count e a variável spray como idependentes
spray
```

Gráfico de barras

```{r}
barplot(spray$count, col = gray.colors(6), xlab="Spray", ylab = "Total", names.arg = spray$spray) #"gray.colors(6)" temos o 6 pq são 6 variáveis categóricas/ "names.arg" = para qual variável vou gerar as barras/"spray$count" é a minha variável numérica
box() #para gerar uma moldura
```
Gráfico de pizza

```{r}
pie(spray$count, labels = spray$spray, main = "Spray", col = c(1:6))
```
Podemos adicionar legendas

```{r}
pie(spray$count, labels = NA, main = "Spray", col = c(1:6))
legend("bottomright", legend = spray$spray, cex=1, fill = c(1:6))
```

Considerações finais
 -> em dados categóricos, vamos sempre passar primeiro o dado numérico


