
```{r}
plot(cars)
```

```{r}
print("Eu te amo Nat")
```
```{r}
getwd()
```
```{r}
class(iris)
```
```{r}
iristeste = iris
save(iristeste,file="iristeste.Rdata")
rm(iristeste)
iristeste
```
```{r}
load(file="iristeste.Rdata")
iristeste
```

```{r}
x = c(12,34,56,79)
y = c(1,6,9,14)
plot(x,y)

```
```{r}
install.packages("e1071")
library(e1071)
```


```{r}
detach("package:e1071",unload = TRUE)
remove.packages("e1071")
```
```{r}
delta = 8
class(delta)
```
```{r}
delta = 8L
class(delta)
```
```{r}
logico = TRUE
caractere = "nat"
class(logico)
class(caractere)
```
```{r}
c = 4
d = 2
(c + d) * d
e = (c + d) * d
e
```

```{r}
a = 4
b = 10
a > b
a != b
sqrt(25)
```
```{r}
x = c(1,2,3,4)
x
x[2] = 11
x
```
```{r}
y = c("a","b","c")
y
z = c(1L,3L,27L)
z
class(y)
class(z)
```
```{r}
VADeaths #matriz que vem no R
colnames(VADeaths)
rownames(VADeaths)
```
```{r}
VADeaths[,1]
VADeaths[1,]
VADeaths[1:3,]
VADeaths[c(1,3,5),]
```
```{r}
#data frame é uma espécie de matriz que aceita mais de um tipo
longley
longley[1:4,1:3]
longley$Unemployed #vira vetor
longley["Unemployed"]
```
```{r}
#LISTAS
ability.cov
ability.cov$cov
ability.cov[1]
ability.cov$center
class(ability.cov$cov)
class(ability.cov$center)
ability.cov$cov[,1:3]
```
```{r}
state.region
```
Fatores são uma maneira de armazenar dados categóricos em R. Dados categóricos são aqueles que representam categorias ou grupos, como cores, tamanhos, tipos, etc. Ao usar fatores, você pode trabalhar de forma mais eficiente com esses tipos de dados em análises estatísticas e gráficos.

```{r}
getwd()
sd
head(x=iris,n=2)
head(iris,2)
head(iris)
help(sd)
```
```{r}
esoph
head(esoph)
tail(esoph)
head(esoph,n=10)
```
```{r}
dim(esoph) #retorna o número de linhas e colunas
dim(esoph)[1]
dim(esoph)[2]
```
```{r}
length(islands) #se usar com vetores bidimensionais retornará o número de colunas
```
```{r}
colnames(esoph)
rownames(esoph)
```
```{r}
summary(esoph) #um resumo
```
```{r}
x = file.choose()
x
```
aqui ele retorna o caminho de um arquivo que o você escolher
```{r}

```

