Minha análise

```{r}
#paleta de cores
library(RColorBrewer)
```

```{r}
dados = read.csv("C:/Users/steph/OneDrive/Documentos/R/dados.csv", sep=";")
head(dados)
```
```{r}
summary(dados$PIB)
summary(dados$VALOREMPENHO)
```
```{r warning=FALSE}
#gráficos base
boxplot(dados$VALOREMPENHO, main = "Valores de empenho",outline = F)
boxplot(dados$PIB, main = "Valores PIB",outline = F)
hist(dados$VALOREMPENHO,main="Valores de Empenho")
hist(dados$PIB,main="Valores de PIB", outline = F )
```
Maiores empenhos

```{r}
Mempenho = head(dados[order(-dados$VALOREMPENHO),],10)
barplot(Mempenho$VALOREMPENHO, main = "Maiores empenhos", col=brewer.pal(n = 10, name = "RdBu"),las = 1)
legend("topright", legend = Mempenho$MUNICIPIO, col=brewer.pal(n = 10, name = "RdBu"), cex = 0.8, ncol = 2, lty = 1:2, lwd = 4)
```
Maiores pibs

```{r}
Mpib = head(dados[order(-dados$PIB),], 10)
barplot(Mpib$PIB, main = "Maiores PIB's", col = brewer.pal(n = 10, name="Spectral"), las = 1)
legend("topright", legend = Mpib$MUNICIPIO, cex = 0.8, ncol = 2, col = brewer.pal(n = 10, name="Spectral"), lty = 1:2, lwd = 4)
```
Relação pib e empenho

```{r warning=FALSE}
dados$PROPORCAO = dados$VALOREMPENHO  / dados$PIB
Mprop = head(dados[order(-dados$PROPORCAO),], 10)
barplot(Mprop$PROPORCAO, main = "Maiores Gastos em Proporção ao PIB", col = brewer.pal(n = 10, name = "Set2"), las = 1)
legend("topright", legend = Mprop$MUNICIPIO, cex = 0.8, ncol = 2, col = brewer.pal(n = 10, name = "Set2"), lty = 1:2, lwd = 4)
```

